var express = require('express');
var router = express.Router();
var notesController = require('../app-server/notes.controller.js');

router.get('/notes/:title', function(req, res, next) {
  res.json([
    {id:"0" , text: "note 0"},
    {id:"1" , text: "note 1"},
    {id:"2" , text: "note 2"},
    {id:"3" , text: "note 3"},
    {id:"4" , text: "note 4"},
    {id:"5" , text: "note 1"},
    {id:"6" , text: "note 2"},
    {id:"7" , text: "note 3"},
    {id:"8" , text: "note 4"},
    {id:"9" , text: "note 1"},
    {id:"10" , text: "note 2"},
    {id:"11" , text: "note 3"},
    {id:"12" , text: "note 4"},
    {id:"13" , text: "note 1"},
    {id:"14" , text: "note 2"},
    {id:"15" , text: "note 3"},
    {id:"16" , text: "note 4"},
    {id:"17" , text: "note 1"},
    {id:"18" , text: "note 2"},
    {id:"19" , text: "note 3"},
    {id:"20" , text: "note 4"},
    {id:"21" , text: "note 1"},
    {id:"22" , text: "note 2"},
    {id:"23" , text: "note 3"},
    {id:"24" , text: "note 4"},
    {id:"25" , text: "note 1"},
    {id:"26" , text: "note 2"},
    {id:"27" , text: "note 3"},
    {id:"28" , text: "note 4"},
    {id:"29" , text: "note 1"},
    {id:"30" , text: "note 2"},
    {id:"31" , text: "note 3"},
    {id:"32" , text: "note 4"},
    {id:"33" , text: "note 1"},
    {id:"34" , text: "note 2"},
    {id:"35" , text: "note 3"},
    {id:"36" , text: "note 4"},
    {id:"37" , text: "note 1"},
    {id:"38" , text: "note 2"},
    {id:"39" , text: "note 3"},
    {id:"40" , text: "note 4"},
    {id:"41" , text: "note 1"},
    {id:"42" , text: "note 2"},
    {id:"43" , text: "note 3"},
    {id:"44" , text: "note 4"},
    {id:"45" , text: "note 1"},
    {id:"46" , text: "note 2"},
    {id:"47" , text: "note 3"},
    {id:"48" , text: "note 4"},
    {id:"49" , text: "note 1"},
    {id:"50" , text: "note 2"},
    {id:"51" , text: "note 3"},
    {id:"52" , text: "note 4"},
    {id:"53" , text: "note 1"},
    {id:"54" , text: "note 2"},
    {id:"55" , text: "note 3"},
    {id:"56" , text: "note 4"},
    {id:"57" , text: "note 1"},
    {id:"58" , text: "note 2"},
    {id:"59" , text: "note 3"},
    {id:"60" , text: "note 4"},
    {id:"61" , text: "note 1"},
    {id:"62" , text: "note 2"},
    {id:"63" , text: "note 3"},
    {id:"64" , text: "note 4"},
    {id:"65" , text: "note 1"},
    {id:"66" , text: "note 2"},
    {id:"67" , text: "note 3"},
    {id:"68" , text: "note 4"},
    {id:"69" , text: "note 1"},
    {id:"70" , text: "note 2"},
    {id:"71" , text: "note 3"},
    {id:"72" , text: "note 4"}]
  );
});

router.get('/topics', function(req, res, next) {
  res.json({topics:[
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"},
    {title: "Topic 1"},
    {title: "Topic 2"},
    {title: "Topic 3"},
    {title: "Topic 4"}]
  });
});

router.post('/postSomething', notesController.saveNotes);

module.exports = router;
